// <auto-generated />
using System;
using BestellSystem.Infrastructur.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestellSystem.Migrations
{
    [DbContext(typeof(BestellDbContext))]
    [Migration("20250714081154_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BestellSystem.Domain.Entities.Bestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Erstellungsdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kunde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bestellungen");
                });

            modelBuilder.Entity("BestellSystem.Domain.ValueObjects.BestellPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestellungId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EinzelPreis")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProduktName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BestellungId");

                    b.ToTable("BestellPosition");
                });

            modelBuilder.Entity("BestellSystem.Domain.ValueObjects.BestellPosition", b =>
                {
                    b.HasOne("BestellSystem.Domain.Entities.Bestellung", null)
                        .WithMany("Positionen")
                        .HasForeignKey("BestellungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BestellSystem.Domain.Entities.Bestellung", b =>
                {
                    b.Navigation("Positionen");
                });
#pragma warning restore 612, 618
        }
    }
}
